# **1. 파이토치(Pytorch)**
* Tensorflow와 함께 머신러닝, 딥러닝에서 가장 널리 사용되는 프레임워크
* 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 파이썬 기반으로 변경한 것이 Pytorch
* 뉴욕대학교와 페이스북(메타)이 공동으로 개발하였고, 현재 가장 대중적인 머신러닝, 딥러닝 프레임워크

In [ ]:
import torch
print(torch.__version__)

2.3.0+cu121


### 1-1. 스칼라(Scalar)
* 하나의 상수를 의미

In [ ]:
var1 = torch.tensor([1])  #torch.tensor(): 자료를 담을 수 있음 => 리스트에 담음
var1

tensor([1])

In [ ]:
type(var1)

torch.Tensor

In [ ]:
var2 = torch.tensor([10.5])  # 실수
var2

tensor([10.5000])

In [ ]:
# 두 스칼라의 사칙 연산
print(var1 + var2)
print(var1 - var2)
print(var1 * var2)
print(var1 / var2)

tensor([11.5000])
tensor([-9.5000])
tensor([10.5000])
tensor([0.0952])


### 1-2. 벡터(Vector)
* 상수가 두 개 이상 나열되었을 경우

In [ ]:
vec1 = torch.tensor([1, 2, 3])
vec1

tensor([1, 2, 3])

In [ ]:
type(vec1)

torch.Tensor

In [ ]:
vec2 = torch.tensor([1.5, 2.4, 3.4])
vec2

tensor([1.5000, 2.4000, 3.4000])

In [ ]:
# 두 벡터의 사칙 연산
print(vec1 + vec2)
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)

tensor([2.5000, 4.4000, 6.4000])
tensor([-0.5000, -0.4000, -0.4000])
tensor([ 1.5000,  4.8000, 10.2000])
tensor([0.6667, 0.8333, 0.8824])


In [ ]:
vec3 = torch.tensor([5, 10, 15, 20])
vec3

tensor([ 5, 10, 15, 20])

In [ ]:
# 사이즈가 다르면 => 에러
vec1 + vec3
# RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

### 1-3. 행렬(Matrix)
* 2개 이상의 벡터 값을 가지고 만들어진 값으로 행과 열의 개념을 가진 숫자의 나열

In [ ]:
mat1 = torch.tensor([[1,2], [3,4]])
print(mat1)

tensor([[1, 2],
        [3, 4]])


In [ ]:
mat2 = torch.tensor([[7,8], [9,10]])
print(mat2)

tensor([[ 7,  8],
        [ 9, 10]])


In [ ]:
# 두 행렬의 사칙 연산 => 같은 포지션끼리 계산됨
print(mat1 + mat2)
print(mat1 - mat2)
print(mat1 * mat2)
print(mat1 / mat2)

tensor([[ 8, 10],
        [12, 14]])
tensor([[-6, -6],
        [-6, -6]])
tensor([[ 7, 16],
        [27, 40]])
tensor([[0.1429, 0.2500],
        [0.3333, 0.4000]])


### 1-4. 텐서(Tensor)
* 다수의 행렬이 모이면 텐서
* 배열이나 행렬과 매우 유사한 특수한 자료구조
* 파이토치는 텐서를 사용하여 모델의 입력과 출력, 모델의 매개변수들을 처리
<center><img src='https://miro.medium.com/max/875/1*jRyyMAhS_NZxqyv3EoLCvg.png' width=500></center>

In [ ]:
tensor1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor1

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [ ]:
tensor2 = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
tensor2

tensor([[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])

In [ ]:
# 두 텐서의 사칙 연산
print(tensor1 + tensor2)
print(tensor1 - tensor2)
print(tensor1 * tensor2)
print(tensor1 / tensor2)

tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])
tensor([[[-8, -8],
         [-8, -8]],

        [[-8, -8],
         [-8, -8]]])
tensor([[[  9,  20],
         [ 33,  48]],

        [[ 65,  84],
         [105, 128]]])
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [ ]:
print(torch.add(tensor1,tensor2))
print(torch.subtract(tensor1,tensor2))
print(torch.multiply(tensor1,tensor2))
print(torch.divide(tensor1,tensor2))
print(torch.matmul(tensor1,tensor2)) # 행렬곱 연산

tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])
tensor([[[-8, -8],
         [-8, -8]],

        [[-8, -8],
         [-8, -8]]])
tensor([[[  9,  20],
         [ 33,  48]],

        [[ 65,  84],
         [105, 128]]])
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])
tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])


In [ ]:
# inplace 연산방법: 모든 사칙 연산자에 _ 를 붙여 사용
print(tensor1.add_(tensor2)) # tensor1에 결과를 다시 저장
print(tensor1.subtract_(tensor2)) # 모든 사칙 연산자에 _ 를 붙이면 inplace=True가 됨

tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### 2. 텐서의 변환

In [ ]:
data = [[1,2], [3,4]]
print(data)

[[1, 2], [3, 4]]


In [ ]:
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
import numpy as np

In [ ]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [ ]:
x_np_1 = torch.tensor(np_array)
x_np_1

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_np_1[0, 0] = 100 # 텐서(x_np_1)  첫 번째 원소를 100으로 변경
print(x_np_1)     # 100으로 바뀜
print(np_array)   # 안 바껴있음

tensor([[100,   2],
        [  3,   4]])
[[1 2]
 [3 4]]


In [ ]:
# as_tensor(): ndarray와 동일한 메모리 주소를 가리키는 뷰를 만듦
# 원본 데이터를 공유
x_np_2 = torch.as_tensor(np_array)
print(x_np_2)
x_np_2[0, 0] = 200 # 기존 메모리 주소의 ndarray 값을 변경하게 됨 => 200으로 바뀜
print(x_np_2)
print(np_array)    # np_array도 200으로 바뀜=> 메모리를 같이 쓴다(동일한 메모리 사용)

tensor([[1, 2],
        [3, 4]])
tensor([[200,   2],
        [  3,   4]])
[[200   2]
 [  3   4]]


In [ ]:
# from_numpy(): ndarray와 동일한 메모리 주소를 가리키는 뷰를 만듦
x_np_3 = torch.from_numpy(np_array) # ndarray와 동일한 메모리 주소를 가리키는 뷰를 만드는 함수
print(x_np_3)
x_np_3[0, 0] = 400 # 기존 메모리 주소의 ndarray 값을 변경하게 됨
print(x_np_3)
print(np_array)    # ndarray도 400으로 바껴있음

tensor([[200,   2],
        [  3,   4]])
tensor([[400,   2],
        [  3,   4]])
[[400   2]
 [  3   4]]


In [ ]:
# 다시 돌리기
# NumPy 배열로 변환
np_again = x_np_3.numpy()
print(np_again, type(np_again))  # => ndarray로 다시 돌아옴

[[400   2]
 [  3   4]] <class 'numpy.ndarray'>


### 3. 파이토치 주요 함수

In [ ]:
# 모든 값이 1로 채워짐
a = torch.ones(2, 3)
print(a)  # => 2행3열 1로 채워진 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# 모든 요소가 0으로 채워짐
b = torch.zeros(2, 3)
print(b)  # => 2행3열 0로 채워진 행렬

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 원하는 값으로 채우기
c = torch.full((2,3), 10)
print(c)

tensor([[10, 10, 10],
        [10, 10, 10]])


In [ ]:
# 무작위 값 넣기
d = torch.empty(2,3) # 실수 무작위값을 넣어줌
print(d)  # 실수 아무값이나 들어감

tensor([[ 3.0466e+33,  7.0065e-45, -9.2656e-11],
        [-7.2829e-01,  8.9683e-44,  0.0000e+00]])


In [ ]:
# 단위 행렬
e = torch.eye(5)
print(e) # 대각선이 1로 채워진 값이 만들어짐

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# 0부터 9까지의 정수
f = torch.arange(10)
print(f) # arange(): 일정한 간격으로 숫자들의 시퀀스를 생성

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# 0과 1 사이의 무작위 실수
g = torch.rand(2, 3) # 랜덤한 숫자를 나열해줌, 0~1 사이의 양수만 출력
print(g)

tensor([[0.4324, 0.7441, 0.2065],
        [0.2154, 0.2670, 0.7713]])


In [ ]:
# 평균이 0이고 표준편차가 1인 정규 분포에서 추출한 무작위 수로 구성
h = torch.randn(2, 3) # 평균이 0이고 표준편차가 1인 정규 분포에서 무작위 샘플링
print(h)

tensor([[-2.0846, -0.4022,  0.7805],
        [ 1.2240,  0.5861,  0.6958]])


In [ ]:
# 0부터 15까지의 정수
i = torch.arange(16).reshape(2, 2, 4) # (2, (2, 4)) 2행 4열 두개라 생각  # 0, 1, 2번이라고 생각
print(i, i.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [ ]:
# 텐서 i의 차원을 변경
# permute(): 차원을 인덱스로 변환
# i = (2, 2, 4)
j = i.permute((2, 0, 1)) # (2, 2, 4) -> (4, 2, 2)   =. 2행 2열 4개
print(j, j.shape)
# 원래 텐서 i의 차원은 (2, 2, 4)
# 이를 (2, 0, 1) 순서로 변경하면 각 차원의 위치가 바뀌어서,
# 첫 번째 차원이 2번째 위치로, 두 번째 차원이 0번째 위치로, 세 번째 차원이 1번째 위치로 이동
# 따라서 k는 4x2x2 크기의 텐서가 됨

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


In [ ]:
# 차원을 인덱스로 변경
k = i.transpose(1, 2) # 1, 2번이 들어옴 # 2, 4, 2
print(k, k.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


### 4. 텐서의 인덱싱과 슬라이싱

In [ ]:
a = torch.arange(1, 13).reshape(3, 4)  # 1~12 벡터를 3행 4열 행렬로
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [ ]:
# 인덱싱하면 차원이 줄어듬
print(a[1])

tensor([5, 6, 7, 8])


In [ ]:
print(a[0, -1])  # -1 직전까지

tensor(4)


In [ ]:
print(a[1:-1])  # 슬라이싱

tensor([[5, 6, 7, 8]])


In [ ]:
print(a[:2, 2:]) # 슬라이싱
# :2는 첫 번째 축(행)에서 처음부터 인덱스 2 미만까지의 범위를 선택 => 즉, 0번째 행부터 1번째 행까지 선택
# 2:는 두 번째 축(열)에서 인덱스 2부터 끝까지의 범위를 선택 => 즉, 2번째 열부터 마지막 열까지 선택

tensor([[3, 4],
        [7, 8]])


# **5. GPU 사용하기**
* 코랩에서 device 변경하는 방법
    * 상단 메뉴 -> 런타임 -> 런타임 유형변경 -> 하드웨어 가속기를 GPU로 변경 -> 저장 -> 다시 시작 및 모두 실행

In [ ]:
tensor = torch.rand(3, 4)
print(tensor)
print(f'shape: {tensor.shape}')
print(f'type: {type(tensor)}')
print(f'dtype: {tensor.dtype}')
print(f'device: {tensor.device}')

tensor([[0.2885, 0.4736, 0.2574, 0.7243],
        [0.3782, 0.2394, 0.7960, 0.9214],
        [0.2156, 0.0106, 0.4487, 0.2621]])
shape: torch.Size([3, 4])
type: <class 'torch.Tensor'>
dtype: torch.float32
device: cpu


In [ ]:
# is_available(): gpu를 사용할 수 있는지 여부
tensor = tensor.reshape(4, 3)
tensor = tensor.int()
print(f'shape: {tensor.shape}')
print(f'type: {type(tensor)}')
print(f'dtype: {tensor.dtype}')    # int32 바뀜

if torch.cuda.is_available():
    print('GPU를 사용할 수 있음')
    tensor = tensor.to('cuda')      # cuda: gpu 속성
print(f'device: {tensor.device}')

# 만약 GPU가 사용 가능하면, 텐서는 CPU에서 GPU로 이동될 것이고
# 만약 GPU가 사용 불가능하면, 텐서는 그대로 CPU에 남아있을 것

shape: torch.Size([4, 3])
type: <class 'torch.Tensor'>
dtype: torch.int32
GPU를 사용할 수 있음
device: cuda:0
