# **1. Iris DataSet(아이리스 데이터셋)**
* 데이터셋: 특정한 작업을 위해 데이터를 관련성 있게 모아놓은 것
* [사이킷런 공식 홈페이지](https://scikit-learn.org/stable/api/sklearn.datasets.html#module-sklearn.datasets)

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris() # 아이리스 붓꽃 데이터
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
print(iris['DESCR']) # DESCR이란 데이터 셋의 설명을 하는것

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

- sepal length in cm: 꽃받침의 길이
- sepal width in cm: 꽃받침의 너비
- petal length in cm: 꽃잎의 길이
- petal width in cm: 꽃잎의 너비

In [ ]:
data = iris['data'] # 샘플데이터, Numpy 배열로 이루어져 있음
data # 결과 보기

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
feature_names = iris['feature_names'] # Feauture 데이터의 이름
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
import pandas as pd

In [ ]:
df_iris = pd.DataFrame(data, columns = feature_names)
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
target = iris['target'] # Label데이터, Numpy 배열로 이루어져 있음
target # 결과보기

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
target.shape  # 150개

(150,)

In [ ]:
# 기존의 df_iris 데이터프레임에 target이라는 새 열을 추가하고, 각 샘플의 클래스 라벨을 해당 열에 삽입
df_iris['target'] = target
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [ ]:
#scikit-learn(sklearn)라이브러리에서 제공하는 train_test_split 함수를 가져오는 구문
# train_test_split 함수는 기계 학습 모델을 훈련(학습) 하기 위해 사용하는 데이터를 훈련세트와 테스트 세트로 나누는데
# 사용됨
# 일반적으로 데이터 세트를 훈련세트와 테스트세트로 분리하여 모델의 성능을 평가하고 검증하기 위해 사용됨
from sklearn.model_selection import train_test_split

In [ ]:
# train_test_split(독립변수, 종속변수, 테스트사이즈 = 0.25, 시드값)
# 데이터프레임 df_iris를 훈련 세트와 테스트 세트로 분할하는 코드
# df_iris.drop('target',1) = 독립변수로 구성된 데이터를 나타냄
# df_iris['target'] = 종속 변수(타깃)으로 구성된 데이터를 나타냄
# train_test_split = 독립변수와 종속변수를 주어진 비율에 따라 훈련 세트와 테스트 세트로 분할
# test_size = 0.2 # 테스트 세트의 크기를 전체 데이터의 20%로 지정하기 위해 사용
# random_state= 10 # 분할 과정에서 데이터를 섞기 위한 난수 발생기의 시드를 설정=> 숫자로 섞임이 고정됨
# x_train = 훈련세트의 독립변수 x_test = 테스트세트의 독립변수 y_train = 훈련세트의 종속변수 y_test = 테스트세트의 종속변수를 나타냄

# df_iris.drop('target', axis=1)는 df_iris 데이터프레임에서 'target'이라는 열(column)을 제거한 결과를 반환하는 메소드입니다.
X_train, X_test, y_train, y_test = train_test_split(df_iris.drop('target', axis=1),
                                                    df_iris['target'],
                                                    test_size=0.2,
                                                    random_state=2024
                                                    )

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df_iris.drop('target', axis=1),
                                                    df_iris['target'],
                                                    test_size=0.2,
                                                    random_state=2023
                                                    )

In [ ]:
# shape는 numpy배열 또는 데이터프레임의 차원을 나타내는 속성
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [ ]:
y_train.shape, y_test.shape

((120,), (30,))

In [ ]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
9                  4.9               3.1                1.5               0.1
38                 4.4               3.0                1.3               0.2
18                 5.7               3.8                1.7               0.3
119                6.0               2.2                5.0               1.5
98                 5.1               2.5                3.0               1.1
..                 ...               ...                ...               ...
52                 6.9               3.1                4.9               1.5
116                6.5               3.0                5.5               1.8
3                  4.6               3.1                1.5               0.2
25                 5.0               3.0                1.6               0.2
87                 6.3               2.3                4.4               1.3

[120 rows x 4 columns]

In [ ]:
y_train

9      0
38     0
18     0
119    2
98     1
      ..
52     1
116    2
3      0
25     0
87     1
Name: target, Length: 120, dtype: int64

In [ ]:
# svm = support vector Machine,SVM) scikit-learn(sklearn)라이브러리에서 제공하는 서포트 백터 머신
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [ ]:
svc = SVC()
svc.fit(X_train, y_train )

SVC()

In [ ]:
# svc.predict()메서드는 주어진 데이터에 대한 예측값을 반환함
y_pred = svc.predict(X_test)
y_pred

array([2, 1, 1, 2, 1, 2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 2, 0, 1, 0, 0, 1, 0,
       2, 1, 0, 0, 0, 2, 1, 0])

In [ ]:
print('정답률:', accuracy_score(y_test, y_pred))
# 셔플 random_state 문제?
# 2024 => 데이터가 쏠렸었음 => 0.866
# 2023 => 잘 맞춤 => 1

정답률: 1.0


In [ ]:
# 6.2 2.1 4.1 1.5
y_pred = svc.predict([[6.2, 2.1, 4.1, 1.5]])
y_pred  # 1번 예측

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1])